### ISSUE TITLE
Add Compatibility With Lucid PHX016S Camera

### ISSUE THREAD

**Issue by electronsandstuff** [whl64/beamview#2]
The B24 beamline and MTE meter use a different model of camera than the rest of the lab.  The property node tree of these cameras is different from the lab's Allied Vision cameras and beamview cannot change settings such as gain and exposure.

To change this, instead of the beamview application maintaining a list of low-level GigE objects with different function names for exposure between camera models, we can create a wrapper class for each camera model that has a uniform interface.

During initialization, beamview can find the model name of the camera and match it against known models and initialize the correct class to populate the list.  Then during execution, the program just needs to know that it is using a list of cameras that all have the same interface.  New cameras in the future will only need to create a new wrapper class and add a line to the "camera factory" that generates wrappers from model names.

**Comment by whl64** [comment]
How exactly is it different? I was under the impression that MATLAB GigE objects were meant to be a universal wrapper.

**Comment by electronsandstuff** [comment]
Yeah, it is "universal".  However, it's so universal that it doesn't define a standard for stuff like the name used for setting exposure, gain, or any number of other parameters.  Those are left up to the manufacturer since some devices may not have gain or stuff like that.

**Comment by electronsandstuff** [comment]
For example, Allied Vision calls exposure `ExposureTimeAbs` while it's called `EXPOSURETIME` on the Lucide cameras.

The dumb thing is that the Genicam standard does have recommendations for this (`ExposureTime`), but nobody seems to follow it.

**Comment by electronsandstuff** [comment]
I guess the other big reason we want a wrapper is that each camera sort of operates like its own little state machine that varies depending on manufacturer and even camera model.

For instance, with the GC650's you have to be careful and set the cameras to the correct mode for single-shot capture, pixel mode and exposure type for it to be compatible with the way we use the cameras.

There's a similar procedure which we will need to use for the Lucid cameras, but is completely different than the allied vision ones.  In fact, for the Lucid cameras, they start off in a state where exposure time is read-only.

**Comment by whl64** [comment]
I see your point. This should definitely be done.

**Comment by electronsandstuff** [comment]
Just tested the branch `add-multiple-camera-support` on the windows B29 computer.  Had to fix one issue with bit depth of Allied Vision cameras not being detected correctly, but everything else seems to be working.  I'll merge into master and close this issue.
