### ISSUE TITLE
Add Optional Prefix for EPICS PVs

### ISSUE THREAD

**Issue by electronsandstuff** [whl64/beamview#3]
Beamview currently pushes beam statistical information onto an EPICS IOC and has hard-coded PV names.  This gets in the way of multiple instances of beamview being used between B29, B24, and the MTE meter.  To solve this, we could add a prefix to the PVs to distinguish them.

We can start using a config file for each beamline which for now will just contain the EPICS prefix.  When EPICS prefix is equal to the empty string, we'll just use the existing PVs for compatibility with everything already set up in B29.  When a prefix is added, then the correct PVs would look something like "PREFIX:sigma_x" with a colon to separate them as seems common for EPICS variable names.

**Comment by whl64** [comment]
I think this would be a good idea, but not strictly necessary, since I believe the policy is to not run any of the three simultaneously. However, for future-proofing, this is probably a good idea.

B24 has its own ioc, so its beamview PVs can go there. Does the MTE meter have its own ioc?

**Comment by electronsandstuff** [comment]
I was talking with Jared and he thinks that the plan is to run three beamview instances at the same time.

Yeah, the three each have their own IOC.  MTE meter actually has its own computer too.

**Comment by whl64** [comment]
Ok, I think this shouldn't be very difficult to do. I can handle the B29 ioc. I think I'll ask Matt to do B24, since he's the main guy there, and you can do the MTE meter?

**Comment by electronsandstuff** [comment]
Sounds good, I have to meet with Matt about EPICS/camera stuff anyways and if you want I can give him a list of records to add.

Also, if you want to be lazy you could probably just leave B29 as is.  That's why I was planning on making it default to the original PVs when it doesn't have a prefix.  That way we don't interrupt any of your scripts that already reference those names.

You could also do like `B29:sigma_x` and stuff like that if you want too.

**Comment by electronsandstuff** [comment]
I added some JSON formatted input files (`jsondecode` is built in to matlab so we don't need to manage more addons) for B29 and B24 under the `EPICS-prefix` branch.

Because the main launcher is made with a GUI wizard, it can't really accept arguments such as a path to a config file.  I made a new launcher function `beamview_main.m` which is able to handle them and also preserved the existing file `beamview_v2_windows.m` for backwards compatibility.  You should be able to use that .bat file in the repo without seeing any differences.

To not interrupt what you guys are doing in B29, I set it up so that if you start the GUI with no arguments or use `beamview_v2_windows.m`, then beamview will default to loading the B29 config file which uses the same PV names that you already have in your scripts.
